# Generated by Django 4.2.5 on 2023-11-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoCurrency',
        ),
    ]
