# Generated by Django 4.0.3 on 2023-11-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_wallet_transaction_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='date_of_birth',
        ),
    ]
