# Generated by Django 4.0.3 on 2023-11-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_userdetails_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cryptocurrencies',
            field=models.JSONField(default=dict),
        ),
    ]
