# Generated by Django 4.0.3 on 2023-11-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userdetails_cryptocurrencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='type',
            field=models.CharField(default='buy', max_length=5),
        ),
    ]
